name: Terraform AzureRM Destroy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:

      # --------------------------------------------------
      # Checkout Repository
      # --------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # --------------------------------------------------
      # Setup Terraform
      # --------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --------------------------------------------------
      # Terraform Init
      # --------------------------------------------------
      - name: Terraform Init
        run: terraform init

      # --------------------------------------------------
      # Azure Login
      # --------------------------------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # --------------------------------------------------
      # Terraform Destroy Plan
      # --------------------------------------------------
      - name: Terraform Destroy Plan
        env:
          TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
          TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
        run: terraform plan -destroy

      # --------------------------------------------------
      # Terraform Destroy
      # --------------------------------------------------
      - name: Terraform Destroy
        env:
          TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
          TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
        run: terraform destroy -auto-approve