name: Terraform AzureRM Destroy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    environment:
      name: terraform-test

    env:
      TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
      TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}

    steps:

      # --------------------------------------------------
      # Checkout
      # --------------------------------------------------

      - name: Checkout
        uses: actions/checkout@v4

      # --------------------------------------------------
      # Terraform
      # --------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --------------------------------------------------
      # Terraform Init
      # --------------------------------------------------

      - name: Terraform Init
        run: terraform init

      # --------------------------------------------------
      # Azure Login
      # --------------------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # --------------------------------------------------
      # Destroy Plan
      # --------------------------------------------------

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=destroy.tfplan

      # --------------------------------------------------
      # Destroy
      # --------------------------------------------------

      - name: Terraform Destroy
        run: terraform apply -auto-approve destroy.tfplan